{
 "title": "Monitoring Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PC Component Get Total",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "component_getComp_count_total{class=\"ro.unibuc.hello.controller.PCComponentController\",exception=\"none\",method=\"getComp\",result=\"success\",}",
     "legendFormat": "Comp Get"
    }
   ]
  },
  {
   "title": "PC Component Get Total Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "component_getComp_time_seconds_sum{class=\"ro.unibuc.hello.controller.PCComponentController\",exception=\"none\",method=\"getComp\",}",
     "legendFormat": "Comp Get Time"
    }
   ]
  },
  {
   "title": "PC Component Add Total",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "component_addComp_count_total{class=\"ro.unibuc.hello.controller.PCComponentController\",exception=\"none\",method=\"addComp\",result=\"success\",}",
     "legendFormat": "Comp Add"
    }
   ]
  },
  {
   "title": "PC Component Add Total Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "component_addComp_time_seconds_sum{class=\"ro.unibuc.hello.controller.PCComponentController\",exception=\"none\",method=\"addComp\",}",
     "legendFormat": "Comp Add Time"
    }
   ]
  },
  {
   "title": "PC Component Delete Total",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "component_deleteComp_count_total{class=\"ro.unibuc.hello.controller.PCComponentController\",exception=\"none\",method=\"addComp\",result=\"success\",}",
     "legendFormat": "Comp Delete"
    }
   ]
  },
  {
   "title": "PC Component Delete Total Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "component_deleteComp_time_seconds_sum{class=\"ro.unibuc.hello.controller.PCComponentController\",exception=\"none\",method=\"addComp\",}",
     "legendFormat": "Comp Delete Time"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{id=\"direct\",}",
     "legendFormat": "Memory"
    }
   ]
  }
 ]
}